### PR TITLE
Hello Javascript!

### PR DESCRIPTION
**Pull request by carolinapowers**

### CODE REVIEW

**Comment by carolinapowers** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/115

**Comment by carolinapowers** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/115

**Comment by TaylorFoster90** [comment]
:+1:

**Comment by johnalxndr** [comment]
:+1: !!!

**Comment by jrutishauser** [comment]
:+1:

**Pull request merged**
