### PR TITLE
08  surf+paddle+rwd

### PR DESCRIPTION
**Pull request by carolinapowers**

### CODE REVIEW

**Comment by carolinapowers** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/101

**Comment by carolinapowers** [comment]
https://github.com/carolinapowers/TIY-Assignments/blob/08--surf%2Bpaddle%2Brwd/pub/index.html

**Comment by eklemen** [comment]
:+1:  great job!

**Comment by jrutishauser** [comment]
:+1:

**Pull request merged**
