### PR TITLE
Feature/05  more layout

### PR DESCRIPTION
**Pull request by carolinapowers**

### CODE REVIEW

**Comment by carolinapowers** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/79

**Comment by eklemen** [comment]
:+1:

**Comment by johnalxndr** [comment]
:+1:

**Comment by jgarcia99** [comment]
:+1:

**Comment by carolinapowers** [comment]
Checklist of Bugs:
- [ ]CSS Layout
- [ ]Nav Bar to the right lined up with website tittle
- [ ]Time floated left
- [ ]Blue vertical line
- [ ]Time, Icon, Article displayed in line
- [ ]Make it liquid

**Pull request merged**
