### PR TITLE
11--coding-dojo

### PR DESCRIPTION
**Pull request by carolinapowers**

### CODE REVIEW

**Comment by carolinapowers** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/148

**Comment by carolinapowers** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/148

**Comment by sak55** [comment]
:+1:  nice blog

**Comment by TaylorFoster90** [comment]
:+1:

**Pull request merged**
