### PR TITLE
Feature/04  surf+paddle

### PR DESCRIPTION
**Pull request by carolinapowers**
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/61

### CODE REVIEW

**Comment by al-the-x** [comment]
You should try committing more frequently and getting feedback on your PR from your peers. When I don't see a lot of commit for a big project like this, that's usually a sign that a developer is bulldogging.

**Comment by carolinapowers** [comment]
@al-the-x I don't know if I'm bulldogging. But, I'm struggling for sure! lol. I'll try to commit more often. I don't see here some of the things I thought I have committed thought. I have to get that figured out.

**Comment by carolinapowers** [comment]
@al-the-x  I have been committing but I haven't been pushing. I think I got that figured out now.

**Comment by mfees** [comment]
:+1:  on the essay @carolinapowers!

I really liked how you explained both mindsets, it helped me remember things to add to mine.
My only suggestion is to condense the explanation a little bit and elaborate on the ways you have experienced these mindsets. If I understood correctly (which lets face it who understands anything lol) I think David wanted us to focus on that aspect.

Defining the mindsets in the beginning definitely helps the reader understand. Great job!

**Comment by jrutishauser** [comment]
:+1: site looks GREAT

**Comment by eklemen** [comment]
:+1:

**Pull request merged**
